# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{jakewendt-simply_sessions}
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["George 'Jake' Wendt"]
  s.date = %q{2011-02-23}
  s.description = %q{A really simple session manager}
  s.email = %q{github@jakewendt.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "app/controllers/sessions_controller.rb",
    "config/routes.rb",
    "generators/simply_sessions/USAGE",
    "generators/simply_sessions/simply_sessions_generator.rb",
    "generators/simply_sessions/templates/autotest_simply_sessions.rb",
    "generators/simply_sessions/templates/simply_sessions.rake",
    "lib/jakewendt-simply_sessions.rb",
    "lib/simply_sessions.rb",
    "lib/simply_sessions/autotest.rb",
    "lib/simply_sessions/controller.rb",
    "lib/simply_sessions/test_helper.rb",
    "lib/simply_sessions/test_tasks.rb",
    "lib/tasks/simply_authorized.rake"
  ]
  s.homepage = %q{http://github.com/jakewendt/simply_sessions}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.5.2}
  s.summary = %q{A simple session manager}
  s.test_files = [
    "test/app/controllers/application_controller.rb",
    "test/app/controllers/home_controller.rb",
    "test/app/models/user.rb",
    "test/config/routes.rb",
    "test/factories.rb",
    "test/functional/simply_sessions/sessions_controller_test.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, ["~> 2"])
    else
      s.add_dependency(%q<rails>, ["~> 2"])
    end
  else
    s.add_dependency(%q<rails>, ["~> 2"])
  end
end

